exclude_patterns = [
    "dist/**",
  "**/node_modules/",

]
[[analyzers]]
name = "javascript"
enabled = true
environment = ["nodejs"]
module_system = "es-modules"
=======

[[analyzers]]
name = "shell"
enabled = true

